trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'



steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: myregtest
- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    containerRegistry: myregtest
    repository: $(imageName)
    tags: |
      tag1

